
services:
  postgres:
    image: postgres:latest
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: jelajah_koding_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d jelajah_koding_dev"]
      interval: 10s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
    driver: local
